# Generated by Django 2.2.2 on 2019-07-23 17:56

import awx.main.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_v360_job_branch_overrirde'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowjobtemplate',
            name='char_prompts',
            field=awx.main.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workflowjobtemplate',
            name='ask_limit_on_launch',
            field=awx.main.fields.AskForField(blank=True, default=False),
        ),
    ]
