# Generated by Django 2.2.4 on 2019-08-22 01:50

import awx.main.fields
from django.db import migrations
import django.db.models.deletion

import logging


logger = logging.getLogger('awx.main.migrations')


def create_inventory_source_roles(apps, schema_editor):
    InventorySource = app.get_model('main', 'InventorySource')
    ct = 0
    for obj in InventorySource.objects.iterator():
        obj.save()
        ct += 1
    logger.info('Created read role for {} inventory sources.'.format(ct))


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_v360_token_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysource',
            name='read_role',
            field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role=['inventory.read_role'], related_name='+', to='main.Role'),
            preserve_default='True',
        ),
        migrations.RunPython(create_inventory_source_roles)
    ]
