# Generated by Django 2.2.8 on 2020-02-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_v361_license_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedjob',
            name='dependencies_processed',
            field=models.BooleanField(default=False, editable=False, help_text='If True, the task manager has already processed potential dependencies for this job.'),
        ),
    ]
