# Generated by Django 2.2.8 on 2020-02-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_v361_license_cleanup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChannelGroup',
        ),
    ]
