# Generated by Django 2.2.11 on 2020-06-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_v370_remove_jobevent_parent_and_hosts'),
        ('main', '0110_v370_instance_ip_address'),
        ('main', '0106_v370_remove_inventory_groups_with_active_failures'),
        ('main', '0114_v370_remove_deprecated_manual_inventory_sources'),
        ('main', '0107_v370_workflow_convergence_api_toggle'),
        ('main', '0102_v370_unifiedjob_canceled'),
        ('main', '0109_v370_job_template_organization_field'),
        ('main', '0112_v370_workflow_node_identifier'),
        ('main', '0104_v370_cleanup_old_scan_jts'),
        ('main', '0100_v370_projectupdate_job_tags'),
        ('main', '0115_v370_schedule_set_null'),
        ('main', '0111_v370_delete_channelgroup'),
        ('main', '0103_v370_remove_computed_fields'),
        ('main', '0108_v370_unifiedjob_dependencies_processed'),
        ('main', '0113_v370_event_bigint'),
        ('main', '0101_v370_generate_new_uuids_for_iso_nodes'),
    ]

    operations = [
    ]
